# main.py

# -*- coding: utf-8 -*-
"""
Created on Mon Mar  3 19:51:29 2025
@author: adria

This file contains the global configuration settings and parameters for the
network simulation. Modifying these values will alter the simulation's behavior
without needing to change the core logic.
"""

# Import functions from our modules
import io_handler as io # Functions for input/output and user interaction
import traffic_generator as tg # Functions to generate traffic
import data_loader # Functions to load input data
import simulation_core as core # Core simulation functions
import ui_components # For the plot selection dialog
import visualization as vis # 3D network visualization
import reporting # KPI calculation and reporting

# Import other necessary libraries
from tqdm import tqdm # For progress bars
import numpy as np # For numerical operations

# %% ===================== SIMULATION PARAMETERS =====================

# --- Request validated simulation parameters from the user ---

t_sim = io.get_validated_input(
    prompt="Enter the simulation time (seconds): ",
    validation_func=lambda x: x > 0,
    error_message="Simulation time must be a positive number.",
    type_converter=float
)
print(f"Simulation time entered: {t_sim} seconds")

pb_gps_vlan = io.get_validated_input(
    prompt="Enter the VLAN for the PB GPS (positive number, or -1 for no VLAN): ",
    validation_func=lambda x: x > 0 or x == -1,
    error_message="VLAN must be a positive integer or -1.",
    type_converter=int
)
print(f"GPS VLAN on PB entered: {pb_gps_vlan}")

sb_gps_vlan = io.get_validated_input(
    prompt="Enter the VLAN for the SB GPS (positive number, or -1 for no VLAN): ",
    validation_func=lambda x: x > 0 or x == -1,
    error_message="VLAN must be a positive integer or -1.",
    type_converter=int
)
print(f"GPS VLAN on SB entered: {sb_gps_vlan}")

pb_gps_priority = io.get_validated_input("Enter the PTP priority for PB GPS packets (1-7): ", lambda x: 1 <= x <= 7, "Priority must be between 1 and 7.", int)
print(f"PTP Priority for PB entered: {pb_gps_priority}")

sb_gps_priority = io.get_validated_input("Enter the PTP priority for SB GPS packets (1-7): ", lambda x: 1 <= x <= 7, "Priority must be between 1 and 7.", int)
print(f"PTP Priority for SB entered: {sb_gps_priority}")

sv_sampling_frequency = io.get_validated_input("Enter the MUs sampling frequency in Hz (e.g., 4800, or 0 to skip): ", lambda x: x >= 0, "Frequency must be a non-negative number.", int)
print(f"SV sampling frequency entered: {sv_sampling_frequency} Hz")

# --- Seed for Random Number Generation ---
use_default_seed = input("\nUse default seed for reproducibility? (y/n): ").lower().strip()
if use_default_seed == 'y':
    simulation_seed = 42 # A default, fixed seed
    print(f"Using default seed: {simulation_seed}")
else:
    simulation_seed = io.get_validated_input(
        prompt="Enter a custom integer seed: ",
        validation_func=lambda x: isinstance(x, int), # Ensure it's an integer
        error_message="Please enter a valid integer.",
        type_converter=int
    )
    print(f"Using custom seed: {simulation_seed}")

# Set the seed for numpy for all subsequent random operations (e.g., in traffic generation)
np.random.seed(simulation_seed)

# Ask user for the data loading mode
load_mode = input("\nLoad files from 'Inputs' folder automatically? (y/n): ").lower().strip()
use_default_folder = (load_mode == 'y')

# %% ===================== DATA LOADING =====================

sim_data = data_loader.load_all_data(use_default_folder=use_default_folder) # Load all necessary data into a dictionary

# %% ===================== VARIABLE INITIALIZATION =====================

# Each dictionary is keyed by equipment name.
# Initialize data structures for the PB simulation.
pb_equipment_packets      = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [])  # Packets generated by each equipment.
pb_arrived_packets        = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [])  # Packets that have arrived at their final destination.
pb_input_port_packets     = io.initialize_dict_by_equipment_and_priority(sim_data['pb_switch_data'], [])  # Packets waiting at input ports, organized by priority at the switch.
pb_input_port_queue_log   = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [[0]*9]) # Log of input port queue size over time at the switch.
pb_output_port_queue_log  = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [[0]*9]) # Log of output port queue size over time at the switch.
pb_output_port_packets    = io.initialize_dict_by_equipment_and_priority(sim_data['pb_switch_data'], []) # Packets waiting at output ports, organized by priority at the switch.
pb_lost_packets_input     = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [])  # Packets lost at input ports due to buffer overflow at the switch.
pb_lost_packets_output    = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [])  # Packets lost at output ports due to buffer overflow at the switch.
pb_link_free_time         = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [0, 0]) # [input_link_free_time, output_link_free_time]
pb_input_link_throughput  = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [[0]*4]) # Throughput log for input links.
pb_output_link_throughput = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [[0]*4]) # Throughput log for output links.
pb_loop_dropped_packets   = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [])  # Packets dropped to prevent loops.
pb_input_link_delays      = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [])  # Delays registered at input links.
pb_output_link_delays     = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], [])  # Delays registered at output links.
pb_input_buffer_sizes     = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], 0)    # Current size of input port buffers.
pb_buffer_sizes           = io.initialize_dict_by_equipment(sim_data['pb_switch_data'], 0)    # Current size of output port buffers.

# Initialize data structures for the SB simulation.
sb_equipment_packets      = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], []) # Packets generated by each equipment.
sb_arrived_packets        = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], []) # Packets that have arrived at their final destination.
sb_input_port_packets     = io.initialize_dict_by_equipment_and_priority(sim_data['sb_switch_data'], []) # Packets waiting at input ports, organized by priority at the switch.
sb_input_port_queue_log   = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], [[0]*9]) # Log of input port queue size over time at the switch.
sb_output_port_queue_log  = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], [[0]*9]) # Log of output port queue size over time at the switch.
sb_output_port_packets    = io.initialize_dict_by_equipment_and_priority(sim_data['sb_switch_data'], []) # Packets waiting at output ports, organized by priority at the switch.
sb_lost_packets_input     = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], []) # Packets lost at input ports due to buffer overflow at the switch.
sb_lost_packets_output    = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], []) # Packets lost at output ports due to buffer overflow at the switch.
sb_link_free_time         = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], [0, 0]) # [input_link_free_time, output_link_free_time]
sb_input_link_throughput  = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], [[0]*4]) # Throughput log for input links.
sb_output_link_throughput = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], [[0]*4]) # Throughput log for output links.
sb_loop_dropped_packets   = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], []) # Packets dropped to prevent loops.
sb_input_link_delays      = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], []) # Delays registered at input links.
sb_output_link_delays     = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], []) # Delays registered at output links.
sb_input_buffer_sizes     = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], 0) # Current size of input port buffers.
sb_buffer_sizes           = io.initialize_dict_by_equipment(sim_data['sb_switch_data'], 0) # Current size of output port buffers.

# %% ===================== INITIAL TRAFFIC GENERATION =====================

# Generate SV packets for the PB
if sv_sampling_frequency > 0:
    print("\nGenerating SV traffic...")
    tg.generate_sv_packets(sim_data['sv_traffic_df'], pb_equipment_packets, t_sim, frequency_hz=sv_sampling_frequency)

# Initialize dictionaries to store GOOSE flow information for PB
pb_dest_goose_info = {}
pb_source_goose_info = {}

# Generate initial GOOSE heartbeat packets for PB
tg.generate_goose_packets(
    goose_flows_df=sim_data['goose_pb_traffic_df'],
    packets_dict=pb_equipment_packets,
    dest_flow_info=pb_dest_goose_info,
    source_flow_info=pb_source_goose_info,
    simulation_time=t_sim
)

# Initialize dictionaries to store GOOSE flow information for SB
sb_dest_goose_info = {}
sb_source_goose_info = {}

# Generate initial GOOSE heartbeat packets for SB
tg.generate_goose_packets(
    goose_flows_df=sim_data['goose_sb_traffic_df'],
    packets_dict=sb_equipment_packets,
    dest_flow_info=sb_dest_goose_info,
    source_flow_info=sb_source_goose_info,
    simulation_time=t_sim
)

# Generate PTP packets for both PB and SB
tg.generate_ptp_packets(t_sim, pb_gps_vlan, pb_gps_priority, pb_equipment_packets)
tg.generate_ptp_packets(t_sim, sb_gps_vlan, sb_gps_priority, sb_equipment_packets, bus_suffix="_SB")

# %% ===================== SIMULATION PREPARATION =====================

# Prepare data for PB
pb_highest_link_speed, pb_switch_queue_log, pb_switch_names, pb_equipment_info = \
    io.prepare_bus_data(sim_data.get('pb_switch_data'))

# Prepare data for SB
sb_highest_link_speed, sb_switch_queue_log, sb_switch_names, sb_equipment_info = \
    io.prepare_bus_data(sim_data.get('sb_switch_data'))

# --- Core Simulation Parameters ---
# These values can be modified by the user to change the simulation's behavior.

port_buffer_size = 4_000_000  # Size of input/output port buffers in bytes. (User configurable)
switch_processing_time = 2e-6 # Fixed processing time for a packet in the switch fabric, in seconds. (User configurable)

# Determine the overall highest link speed to calculate the simulation time step (delta_t).
overall_highest_speed = max(pb_highest_link_speed, sb_highest_link_speed)
if overall_highest_speed > 0:
    # delta_t is the simulation time step, calculated based on the fastest link to ensure no events are missed.
    delta_t = (10 * 8) / (overall_highest_speed * 1e6)
    print(f"\nOverall highest link speed: {overall_highest_speed} Mbps. Calculated delta_t: {delta_t:.2e} s")
else:
    # Fallback if no link speeds are defined.
    delta_t = 1e-7
    print("\nWarning: No link speeds found. Using default delta_t.")

# --- Simulation Time Control ---
current_time = delta_t
total_steps = int(t_sim / delta_t)

# Initialize switch free time trackers for both buses.
pb_switch_free_time = [0] * sim_data.get('pb_switch_count', 0)
sb_switch_free_time = [0] * sim_data.get('sb_switch_count', 0)

# --- GOOSE Fault and Response Handling Preparation ---

# Pre-sort GOOSE faults by time to process them efficiently during the simulation.
if 'goose_faults_df' in sim_data:
    sim_data['goose_faults_df'] = sim_data['goose_faults_df'].sort_values("TIME (seconds)").reset_index(drop=True)
fault_pointer = 0 # A pointer to keep track of processed faults.

# Create quick-lookup dictionaries for GOOSE responses triggered on each bus.
goose_responses_df = sim_data.get('goose_responses_df')
pb_response_actions = io.create_response_action_dict(goose_responses_df, 'PB')
sb_response_actions = io.create_response_action_dict(goose_responses_df, 'SB')

# %% ===================== MAIN SIMULATION LOOP =====================

print("\n--- Starting Main Simulation Loop ---")
# Use tqdm to display a progress bar for the simulation
with tqdm(total=total_steps, desc="Simulation Progress", unit="step") as pbar:
    while current_time <= t_sim: # Main simulation loop
        # --- PB and SB Processing ---

        # Process GOOSE logic first to handle high-priority messages
        for equipment in pb_arrived_packets: 
            if (pb_arrived_packets[equipment] and pb_arrived_packets[equipment][-1][-1] <= current_time and pb_arrived_packets[equipment][-1][4] == "GOOSE"):
                core.process_goose_logic(equipment, pb_arrived_packets, pb_dest_goose_info, pb_response_actions, sim_data.get('goose_pb_traffic_df'), sim_data.get('goose_sb_traffic_df'), pb_source_goose_info, sb_source_goose_info, pb_equipment_packets, sb_equipment_packets, current_time, t_sim)
        # Process GOOSE logic for SB
        for equipment in sb_arrived_packets:
            if (sb_arrived_packets[equipment] and sb_arrived_packets[equipment][-1][-1] <= current_time and sb_arrived_packets[equipment][-1][4] == "GOOSE"):
                core.process_goose_logic(equipment, sb_arrived_packets, sb_dest_goose_info, sb_response_actions, sim_data.get('goose_pb_traffic_df'), sim_data.get('goose_sb_traffic_df'), pb_source_goose_info, sb_source_goose_info, pb_equipment_packets, sb_equipment_packets, current_time, t_sim)
        
        # Process output port overflows for both buses
        core.process_output_port_overflow(pb_output_port_packets, pb_lost_packets_output, port_buffer_size, pb_buffer_sizes, pb_output_port_queue_log, current_time)
        core.process_output_port_overflow(sb_output_port_packets, sb_lost_packets_output, port_buffer_size, sb_buffer_sizes, sb_output_port_queue_log, current_time)
        
        # Process output queues for both buses
        core.process_output_queues(pb_output_port_packets, pb_link_free_time, pb_equipment_info, pb_output_link_throughput, pb_arrived_packets, pb_output_link_delays, pb_input_link_throughput, pb_input_link_delays, pb_input_port_packets, pb_input_port_queue_log, pb_output_port_queue_log, pb_switch_queue_log, pb_switch_names, pb_loop_dropped_packets, current_time, pb_buffer_sizes)
        core.process_output_queues(sb_output_port_packets, sb_link_free_time, sb_equipment_info, sb_output_link_throughput, sb_arrived_packets, sb_output_link_delays, sb_input_link_throughput, sb_input_link_delays, sb_input_port_packets, sb_input_port_queue_log, sb_output_port_queue_log, sb_switch_queue_log, sb_switch_names, sb_loop_dropped_packets, current_time, sb_buffer_sizes)
        
        # Process input port overflows for both buses
        pb_ready_packets = core.process_input_queues(pb_input_port_packets, pb_lost_packets_input, port_buffer_size, pb_equipment_info, sim_data.get('pb_switch_count', 0), current_time, pb_input_buffer_sizes, pb_input_port_queue_log)
        sb_ready_packets = core.process_input_queues(sb_input_port_packets, sb_lost_packets_input, port_buffer_size, sb_equipment_info, sim_data.get('sb_switch_count', 0), current_time, sb_input_buffer_sizes, sb_input_port_queue_log)
        
        # Process switch forwarding for both buses
        core.process_switch_forwarding(pb_ready_packets, pb_input_port_packets, pb_output_port_packets, pb_input_port_queue_log, pb_output_port_queue_log, pb_switch_queue_log, pb_switch_free_time, pb_equipment_info, pb_switch_names, sim_data.get('pb_vlan_table', {}), current_time, switch_processing_time, pb_buffer_sizes, pb_input_buffer_sizes)
        core.process_switch_forwarding(sb_ready_packets, sb_input_port_packets, sb_output_port_packets, sb_input_port_queue_log, sb_output_port_queue_log, sb_switch_queue_log, sb_switch_free_time, sb_equipment_info, sb_switch_names, sim_data.get('sb_vlan_table', {}), current_time, switch_processing_time, sb_buffer_sizes, sb_input_buffer_sizes)
        
        # Process equipment to port transmissions for both buses
        core.process_equipment_to_port(pb_equipment_packets, pb_link_free_time, pb_equipment_info, pb_switch_names, pb_input_link_throughput, pb_input_port_packets, pb_input_port_queue_log, pb_switch_queue_log, pb_input_link_delays, current_time, pb_input_buffer_sizes)
        core.process_equipment_to_port(sb_equipment_packets, sb_link_free_time, sb_equipment_info, sb_switch_names, sb_input_link_throughput, sb_input_port_packets, sb_input_port_queue_log, sb_switch_queue_log, sb_input_link_delays, current_time, sb_input_buffer_sizes)

        # --- Global Fault Processing ---
        sim_data['goose_faults_df'], fault_pointer = core.process_faults(
            sim_data.get('goose_faults_df'), delta_t, current_time, t_sim,
            pb_equipment_packets, sim_data.get('goose_pb_traffic_df'), pb_source_goose_info,
            sb_equipment_packets, sim_data.get('goose_sb_traffic_df'), sb_source_goose_info,
            fault_pointer
        )
                
        # Advance simulation time
        current_time += delta_t
        pbar.update(1)

# %% ===================== KPI CALCULATION AND ANALYSIS =====================

# Process and save KPIs for the PB
pb_traffic_dfs = {
    'sv': sim_data.get('sv_traffic_df'),
    'goose_pb': sim_data.get('goose_pb_traffic_df')
}
th_in_pb, delay_in_pb, th_out_pb, delay_out_pb, pb_lost_by_flow = reporting.calculate_and_save_kpis(
    'PB', t_sim, pb_equipment_info, pb_switch_names,
    pb_input_link_throughput, pb_input_link_delays, pb_output_link_throughput, pb_output_link_delays,
    pb_switch_queue_log, pb_input_port_queue_log, pb_output_port_queue_log,
    pb_arrived_packets, pb_lost_packets_input, pb_lost_packets_output, pb_traffic_dfs
)

# Process and save KPIs for the SB
sb_traffic_dfs = {
    'goose_sb': sim_data.get('goose_sb_traffic_df')
}
th_in_sb, delay_in_sb, th_out_sb, delay_out_sb, sb_lost_by_flow = reporting.calculate_and_save_kpis(
    'SB', t_sim, sb_equipment_info, sb_switch_names,
    sb_input_link_throughput, sb_input_link_delays, sb_output_link_throughput, sb_output_link_delays,
    sb_switch_queue_log, sb_input_port_queue_log, sb_output_port_queue_log,
    sb_arrived_packets, sb_lost_packets_input, sb_lost_packets_output, sb_traffic_dfs
) 

# %% ===================== DETAILED PLOT GENERATION (OPTIONAL) =====================

plot_choice = input("\nDo you want to generate detailed plots for specific links and ports? (y/n): ").lower().strip()
if plot_choice == 'y':
    print("Opening plot selection window...")
    selected_links, selected_metrics = ui_components.PlotSelectionDialog.run_dialog(
        pb_equipment_info, sb_equipment_info, pb_switch_names, sb_switch_names
    )
    if selected_links and selected_metrics:
        print(f"Generating plots for {len(selected_links)} selected links...")
        reporting.plot_selected_kpis(
            selected_links, selected_metrics,
            pb_arrived_packets, sb_arrived_packets,
            pb_input_port_queue_log, sb_input_port_queue_log, # Correct
            pb_output_port_queue_log, sb_output_port_queue_log, # Correct
            pb_input_link_throughput, sb_input_link_throughput, # Correct
            pb_output_link_throughput, sb_output_link_throughput, # Correct
            t_sim,
            pb_equipment_info,
            sb_equipment_info
        )

plot_flow_choice = input("\nDo you want to generate detailed plots for specific flows? (y/n): ").lower().strip()
if plot_flow_choice == 'y':
    print("Opening flow selection window...")
    selected_flows, selected_metrics = ui_components.FlowPlotSelectionDialog.run_dialog(
        pb_arrived_packets, sb_arrived_packets
    )
    if selected_flows:
        reporting.plot_selected_flows(
            selected_flows, selected_metrics, t_sim, 
            pb_arrived_packets, sb_arrived_packets, 
            pb_lost_by_flow, sb_lost_by_flow
        )


# %% ===================== 3D NETWORK VISUALIZATION =====================

plot_3d_choice = input("\nDo you want to display the 3D network graph? (y/n): ").lower().strip()
if plot_3d_choice == 'y':
    print("\n--- Generating Unified 3D Network Visualization ---")

    # Visualize the complete, interconnected network topology in a single plot
    vis.create_unified_network_visualization(
        pb_equipment_info, sim_data.get('pb_switch_data', {}),
        sb_equipment_info, sim_data.get('sb_switch_data', {}),
        pb_equipment_packets, sb_equipment_packets,
        # Pass throughput data for link coloring
        th_in_pb, th_out_pb,
        th_in_sb, th_out_sb,
        # Pass delay data for node coloring
        delay_out_pb, delay_out_sb
    )
# --- added for the paper figure: per-packet trace of the SV frames received by the BBP
import csv as _csv
with open('trace_BBP_SV.csv', 'w', newline='') as _fh:
    _w = _csv.writer(_fh)
    _w.writerow(['source', 'flow_id', 't_gen', 't_arrival'])
    for _p in pb_arrived_packets.get('BBP', []):
        if _p[4] == 'SV':
            _w.writerow([_p[3], _p[5], _p[8], _p[-1]])
